name: CI/CD Test
on:
   push:
     branches:
       - "master"
jobs:
      Test_On_PUSH_CICD:
        runs-on: ubuntu-latest
        steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v1
           with:
            node-version: 16
         - run: npm install
         - run: npm test
         - run: npm run build
